#!/bin/bash
#
# Launch point for the docker container to run Candlepin tests.
#
# Starts supervisor to manage services, then tries to cd to the correct
# location, either /candlepin-dev if you mounted this as a volume when
# running your container, otherwise the included /candlepin clone which
# we will make sure to update.
#
# See usage below.

# Exit on any error:
set -e

export JAVA_HOME=/usr/lib/jvm/java-1.7.0/
export SUPERVISOR=1
export AUTOCONF=1

launchshell () {
  if [ -n "$LAUNCHSHELL" ]; then
      /bin/bash
  fi
}

EXITMSG="Error occured, exiting. Shell will be launched if -s was used first ('-s -a -b' vs '-a -b -s'."
on_exit () {
    echo "$EXITMSG"
    launchshell
}
trap on_exit EXIT

function usage
{
    cat <<HELP
    usage: candlepin-test [options]

    OPTIONS:
        -r  run rspec test suite
        -u  run unit test suite
        -s  run a bash shell when done
        -c  git reference to checkout
        -t  rspec filter to run specific tests
HELP
}

while getopts ":srutc:" opt; do
    case $opt in
        r  ) RSPEC="1" ;;
        u  ) UNITTEST="1";;
        s  ) LAUNCHSHELL="1";;
        t  ) RSPEC_FILTER="${OPTARG}";;
        c  )
            CHECKOUT="${OPTARG}"
            ;;
        ?  ) FAIL="1";;
    esac
done

# Show usage and exit on bad cli options, unless
# one was '-s' (and before the failure), then
# try to launch a shell to help debugging.
if [ -n "$FAIL" ] ; then
    usage
    launchshell
    exit
fi

shift $(($OPTIND - 1))

# WARNING: control+c while this is running will take out supervisor as well.
/usr/bin/supervisord -c /etc/supervisord.conf &

# Pass volume with docker run mounted at this location if you'd like to
# run against your source checkout.
# i.e. -v /home/dgoodwin/src/candlepin:/candlepin-dev
if [ -d "/candlepin-dev" ]; then
    echo "Using mounted volume /candlepin-dev"
    cd /candlepin-dev/server
else
    # Otherwise we use the clone in the image and try to update it.
    echo "Using /candlepin."
    cd /candlepin/server
    git pull
    if [ ! -z "$CHECKOUT" ]; then
        echo "Checking out: $CHECKOUT"
        git checkout $CHECKOUT
    fi
fi

# Make sure we update the ruby bundle:
bundle install

# TODO: keep track of return code?

if [ "$UNITTEST" == "1" ]; then
    echo "Running unit tests."
    buildr test
fi

if [ "$RSPEC" == "1" ]; then
    echo "Running rspec tests with filter: ${RSPEC_FILTER}"
    bin/deploy -g

    if [ ! -z "$RSPEC_FILTER" ]; then
        buildr "rspec:${RSPEC_FILTER}"
    else
        buildr rspec
    fi

    # If the caller mounted a volume at /artifacts, copy server logs out:
    if [ -d "/artifacts" ]; then
        echo "Copying logs to /artifacts."
        cp -v /var/log/candlepin/access.log /artifacts/
        cp -v /var/log/candlepin/audit.log /artifacts/
        cp -v /var/log/candlepin/candlepin.log /artifacts/
        cp -v /var/log/candlepin/error.log /artifacts/
    fi
fi

launchshell
